name: Deploy Pygame to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pygbag
        run: |
          python -m pip install --upgrade pip
          pip install pygbag pygame-ce

      - name: Build game for web
        run: |
          mkdir dist
          cp game.py dist/
          cp index.html dist/
          mv dist/game.py dist/main.py
          python -m pygbag --archive dist/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
